flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    city = SelectField(
        "City",
        choices=[
            "San Francisco",
            "Seoul",
            "Taipei",
            "Hyderabad",
            "Buenos Aires",
            "London",
            "Berlin",
        ],
        coerce=str,
    )

    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")


class CommentForm(FlaskForm):
    content = TextAreaField("Content", validators=[DataRequired()])
    submit = SubmitField("Post")

flaskblog/cities/routes.py
from flask import Blueprint, flash, render_template, url_for, redirect, abort, request
from flaskblog.models import Post

cities = Blueprint("cities", __name__)


@cities.route("/cities/<string:city>")
def cities_posts(city):
    page = request.args.get("page", 1, type=int)
    # posts = Post.query.filter_by(city=city).first_or_404()
    posts = (
        Post.query.filter_by(city=city)
        .order_by(Post.date_posted.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("city_posts.html", posts=posts, city=city)

flaskblog/main/routes.py
from flask import Blueprint, render_template, request
from flaskblog.models import Post

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get("page", 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
    return render_template("home.html", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html", title="About")

flaskblog/posts/routes.py
from flask import Blueprint, flash, render_template, url_for, redirect, abort, request
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.posts.forms import PostForm, CommentForm
from flaskblog.models import Post, Comment

posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=["POST", "GET"])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            city=form.city.data,
            content=form.content.data,
            author=current_user,
        )
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", "success")
        return redirect(url_for("main.home"))

    return render_template(
        "new_post.html", title="New Post", form=form, legend="New Post"
    )


@posts.route("/post/<int:post_id>/comments/new", methods=["POST", "GET"])
@login_required
def new_comment(post_id):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    if form.validate_on_submit():
        comment = Comment(
            content=form.content.data,
            post=post,
            author=current_user,
        )
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been added!", "success")
        return redirect(url_for("posts.post", post_id=post_id))

    return render_template(
        "new_comment.html",
        title="New Comment",
        form=form,
        legend="New Comment - " + post.title,
    )


@posts.route(
    "/post/<int:post_id>/comments/<int:comment_id>/delete", methods=["POST", "GET"]
)
@login_required
def delete_comment(comment_id, post_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.author != current_user:
        abort(403)

    db.session.delete(comment)
    db.session.commit()

    flash("Your comment has been deleted!", "success")
    return redirect(url_for("posts.post", post_id=post_id))


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post=post).order_by(Comment.date_posted.desc())
    return render_template(
        "post.html",
        title=post.title,
        post=post,
        comments=comments,
    )


@posts.route("/post/<int:post_id>/update", methods=["POST", "GET"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.city = form.city.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated!", "success")

        return redirect(url_for("posts.post", post_id=post.id))

    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content

    return render_template(
        "new_post.html", title="Update Post", form=form, legend="Update Post", post=post
    )


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()

    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.home"))

flaskblog/users/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template, request
from flaskblog import db, bcrypt
from flaskblog.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from flaskblog.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode("utf-8")

        user = User(
            username=form.username.data, email=form.email.data, password=hashed_pw
        )
        db.session.add(user)
        db.session.commit()

        flash(f"Your account has been created! You are now able to log in", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login unsuccessful. Please check email and password", "danger")

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    form = UpdateAccountForm()

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            db.session.commit()

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f"Your account has been updated!", "success")
        return redirect(url_for("users.account"))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template(
        "account.html", title="Account", image_file=image_file, form=form
    )


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = (
        Post.query.filter_by(author=user)
        .order_by(Post.date_posted.desc())
        .paginate(page=page, per_page=5)
    )
    return render_template("user_posts.html", posts=posts, user=user)


@users.route("/reset_password", methods=["GET", "POST"])
def request_reset_password():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Email to reset password sent", "info")
        return redirect(url_for("users.login"))
    return render_template("request_reset.html", form=form, title="Reset Password")


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if not user:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("users.request_reset_password"))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user.password = hashed_pw
        db.session.commit()

        flash(
            f"{user.username} Your password has been updated! You are now able to login",
            "success",
        )
        return redirect(url_for("users.login"))
    return render_template("reset_password.html", title="Reset Password", form=form)

flaskblog/templates/about.html
{% extends 'layout.html' %}

{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends 'layout.html' %}

{% block content %}

    <h1>{{ current_user.username.title() }}'s account!</h1>
    <div class="content-section">
        <div class="media">
            <!-- what is the error below -->
            <img class="rounded-circle account-img" src="{{ image_file }}" alt="profile pic">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username.title() }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <!-- FORM HERE -->
        <div class="content-section">
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Update Profile</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        {% if form.username.errors %}

                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}

                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span><br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

flaskblog/templates/city_posts.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="mb-3">Posts for {{ city }}</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username.title() }}</a>
                    <a href="{{ url_for('cities.cities_posts', city=post.city) }}"><small >{{ post.city }}</small></a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }} </small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}   
                <a class="btn btn-info mb-4" href="{{ url_for('cities.cities_posts', city=city, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('cities.cities_posts', city=city, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username.title() }}</a>
                    <a href="{{ url_for('cities.cities_posts', city=post.city) }}"><small >{{ post.city }}</small></a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }} </small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}   
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

        {% if title %}
        <title>CitySpotlight - {{ title }}</title>
        {% else %}
        <title>CitySpotlight</title>
        {% endif %}
    </head>
    <body>
        <header class="'site-header">
            <nav class="'navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">CitySpotlight</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            {% if current_user.is_authenticated %}
                                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Create Post</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                <div class="col-sm-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                            {{ message }}
                            </div>
                        {% endfor %}
                        {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                </div>
                <div class="col-md-4">
                    <div class="content-section">
                        <h3>Our Sidebar</h3>
                        <p class="text-muted">Rotation Cities
                            <ul class="list-group list-group-item-action list-group-flush">

                                <a href="{{ url_for('cities.cities_posts', city='San Francisco') }}" class="list-group-item list-group-item-action list-group-item-light">San Francisco</a>
                                <a href="{{ url_for('cities.cities_posts', city='Seoul') }}" class="list-group-item list-group-item-action list-group-item-light">Seoul</a>
                                <a href="{{ url_for('cities.cities_posts', city='Taipei') }}" class="list-group-item list-group-item-action list-group-item-light">Taipei</a>
                                <a href="{{ url_for('cities.cities_posts', city='Hyderabad') }}" class="list-group-item list-group-item-action list-group-item-light">Hyderabad</a>
                                <a href="{{ url_for('cities.cities_posts', city='Buenos Aires') }}" class="list-group-item list-group-item-action list-group-item-light">Buenos Aires</a>
                                <a href="{{ url_for('cities.cities_posts', city='London') }}" class="list-group-item list-group-item-action list-group-item-light">London</a>
                                <a href="{{ url_for('cities.cities_posts', city='Berlin') }}" class="list-group-item list-group-item-action list-group-item-light">Berlin</a>

                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    
    </body>
</html>

flaskblog/templates/login.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{url_for('users.request_reset_password')}}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{url_for('users.register')}}">Sign up now</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/new_comment.html
{% extends 'layout.html' %}

{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>

            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}

                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>

                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends 'layout.html' %}

{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username.title() }}</a>
            <a href="{{ url_for('cities.cities_posts', city=post.city) }}"><small >{{ post.city }}</small></a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }} </small>
        </div>
        <h2 class="article-title" href="#">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
        {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.new_comment', post_id=post.id) }}">Add Comment</a>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update Post</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deletePostModal">Delete Post</button>
            </div>
        {% else %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.new_comment', post_id=post.id) }}">Add Comment</a>
          </div>
        {% endif %}
        <div class="article-metadata mt-3">
          <h6><strong>Comments</strong></h6>
        </div>
        {% for comment in comments %}
          <div class="media">
            <a href="{{ url_for('users.user_posts', username=post.author.username) }}"><img class="rounded-circle comment-img" src="{{ url_for('static', filename='profile_pics/' + comment.author.image_file) }}"></a>
            <div class="media-body">
              <small class="mt-1 mb-0">{{ comment.author.username }}</small>
              <small class="ml-3 text-muted">{{ comment.date_posted.strftime('%Y-%m-%d') }} </small><br>
              {{comment.content}}
            </div>
            {% if post.author == current_user %}
              <div>
                <a class="btn btn-danger btn-sm m-1" href="{{ url_for('posts.delete_comment', post_id=post.id, comment_id=comment.id) }}">Delete</a>
              </div>
            {% endif %}
          </div> 
        {% endfor %}
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deletePostModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

flaskblog/templates/request_reset.html
{% extends 'layout.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Password Reset Request</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username.title() }}</a>
                    <a href="{{ url_for('cities.cities_posts', city=post.city) }}"><small >{{ post.city }}</small></a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }} </small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}   
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}